name = "GRMakie"
uuid = "901f954c-a098-49c8-905f-8488b748c16b"
authors = ["Simon Danisch", "Josef Heinen", "Anshul Singhvi"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"

[compat]
AbstractPlotting = "0.9"
GR = "0.46, 0.47"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
